<a href="https://colab.research.google.com/github/19PA1A0292/AI-Lab/blob/master/experiment%201%3A%20Numpy%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 Experiment 1: Numpy

 1)Different ways to create a Numpy arrays

In [1]:
 
[ ]
import numpy as np 
p=np.array([1,2,3])
print(p)

[1 2 3]


 2) ADD,REMOVE, MODIFY array elements add

Add

In [2]:
 
f=np.array([4,8,9])
q=np.append(f,[6,5,8])
print(q)

[4 8 9 6 5 8]


Remove

In [3]:
 
c=np.delete(f,2)
print(c)

[4 8]


Modify

In [4]:
 
c[c>3]=-1
print(c)

[-1 -1]


 3) Arthematic operations on Numpy array

In [5]:
 
import numpy as np 
l=np.random.random((5,5))
m=np.random.random((5,5))
num_sum=np.add(l,m)
num_diff=np.subtract(l,m)
num_prod=np.multiply(l,m)
num_quo=np.divide(l,m)
num_mod=np.mod(l,m)
num_pow=np.power(l,m)
print(num_sum)
print(num_diff)
print(num_prod)
print(num_quo)
print(num_mod)
print(num_pow)

[[0.50317155 1.45568036 0.90531808 1.07440541 0.73274781]
 [0.44408861 1.54922635 0.75554397 0.93877489 1.50913697]
 [0.41407494 0.46678794 0.31768947 0.67064238 0.62448104]
 [1.22848945 1.07765934 0.68902506 0.58142331 1.09476977]
 [0.22276967 1.5376917  1.1209333  0.61397068 0.63093321]]
[[-0.10979944 -0.02690033  0.75449704  0.00158685  0.57605232]
 [-0.17909285 -0.40108286  0.59721277  0.75491572  0.23134727]
 [ 0.06718753  0.04619338  0.09229179  0.44066246  0.37577698]
 [ 0.19229145 -0.13160841  0.60337286  0.013362    0.19450899]
 [-0.22153206  0.24365861 -0.66064668 -0.32782241 -0.20843166]]
[[6.02814238e-02 5.29570419e-01 6.25837606e-02 2.88586115e-01
  5.12707669e-02]
 [4.12851115e-02 5.59808703e-01 5.35458966e-02 7.78501386e-02
  5.55993211e-01]
 [4.17359720e-02 5.39392870e-02 2.31022067e-02 6.38944508e-02
  6.21920593e-02]
 [3.68052583e-01 2.86007222e-01 2.76741798e-02 8.44686302e-02
  2.90171777e-01]
 [1.37468104e-04 5.76281559e-01 2.05009356e-01 6.73731172e-02
  8.8658239

 4)slicing and iterating of numpy array Slicing

Slicing

In [6]:
 
import numpy as np 
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:6])

[2 3 4 5 6]


Iterating

In [7]:
 
for x in arr:
  print(x)

1
2
3
4
5
6
7


 5) matrix operations on bumpy arrays

In [8]:
 
[ ]
import numpy as np 
s=np.array([[1,2],[3,4]])
t=np.array([[5,6],[7,8]])
print(np.add(s,t))
print(np.subtract(s,t))
print(np.divide(s,t))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
